# Development / Testing image for C++ CMake template project

# base image used as the starting point for this image
FROM debian:latest

# ENV DEBIAN_FRONTEND=noninteractive

# Adding all required packages to the image
RUN apt-get update \
    && apt-get install -y \
		apt-utils \
        git \
		build-essential \
        libtool autoconf pkg-config \
        clang \
        llvm \
        libc++-dev libc++abi-dev \
        cmake \        
		libboost-all-dev \
        ccache \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Enviroment variables
ENV CC=/usr/bin/clang
ENV CXX=/usr/bin/clang++

# Variable that can be overwritten at build time of the image
ARG TEST_VAR_DOCKERFILE=test

# ↑ Setup build environment
# ↓ Build and compile project

# Copying the actual folder of the project into the cointainer filesystem
COPY ProjectFolder /ProjectFolder

# Setting the working directory inside the project folder
WORKDIR /

# Running Cmake build script, all cmake files are generated
RUN ProjectFolder/scripts/build_cmake.sh

# Building the project using the build files generated by Cmake
RUN ProjectFolder/scripts/make_debug.sh

WORKDIR /build/debug/tests

# The command that is run by default when the container starts
CMD ["ctest",  "--output-on-failure"]
# Run this to launch the project binary instead
# CMD ["./ProjectFolder/build/debug/bin/cpp-cmake-template"]
