name: cpp-cmake-template
on:
  push:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  windows:
    name: windows
    runs-on: windows-2019
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: configure CMake
      run: cmake -SProjectFolder --preset Debug
    - name: build project
      run: cmake --build build/Debug/
    - name: run tests
      run: ./ProjectFolder/scripts/run_tests.sh
  macos:
    name: macos
    runs-on: macos-11
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - name: configure CMake
      run: ./ProjectFolder/scripts/build_cmake_debug.sh
    - name: build project
      run: ./ProjectFolder/scripts/build_debug.sh
    - name: run tests
      run: ./ProjectFolder/scripts/run_tests.sh
  linux:
    name: linux
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - name: configure CMake
      run: ./ProjectFolder/scripts/build_cmake_debug.sh
    - name: build project
      run: ./ProjectFolder/scripts/build_debug.sh
    - name: run tests
      run: ./ProjectFolder/scripts/run_tests.sh
