name: Build and test on Linux
on:
  workflow_call:

concurrency:
  group: "${{ github.ref }}-linux"
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-20.04
    # Specify an image from hub.docker.com
    # container:
      # image: debian:10-slim
      # options:
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - name: configure CMake
      run: ./ProjectFolder/scripts/build_cmake_debug.sh
    - name: build project
      run: ./ProjectFolder/scripts/build_debug.sh
    - name: run tests
      run: ./ProjectFolder/scripts/run_tests.sh
