name: Build and test on macOS
on:
  workflow_call:

concurrency:
  group: "${{ github.ref }}-macos"
  cancel-in-progress: true

jobs:
  macos:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - name: Setup sccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        max-size: 1000M
        variant: sccache
    - name: Configure CMake and build
      run: ${{ github.workspace }}/projectFolder/scripts/create_release.sh withTests
    - name: Run tests
      run: ${{ github.workspace }}/projectFolder/scripts/run_tests.sh Release
    - uses: actions/upload-artifact@v3
      if: success()
      with:
        name: "macos-artifacts"
        retention-days: 28
        path: |-
          build/Release/bin/cpp-cmake-template
