name: Build and test on Windows
on:
  workflow_call:

concurrency:
  group: "${{ github.ref }}-windows"
  cancel-in-progress: true

jobs:
  windows:
    name: windows
    runs-on: windows-2019
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - name: configure CMake
      run: cmake -SProjectFolder --preset Debug
    - name: build project
      run: cmake --build build/Debug/
    - name: run tests
      run: ctest --output-on-failure --test-dir build/Debug/tests
